version: "3.9"
services:
  # Watchtower service to manage updates
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  # Sandypi image
  sandypi:
    image: texx00/sandypi
    restart: unless-stopped
    volumes:
      - database:/database
      - static:/sandypi/server/static
      - saves:/sandypi/server/saves
      - autodetect:/sandypi/server/autodetect
      - logs:/sandypi/server/logs
      - /dev:/dev                               # this is necessary to access the usb drive to control the device
      - /sbin/shutdown:/sbin/shutdown           # necessary to shutdown the device
      - /sbin/reboot:/sbin/reboot               # necessary to reboot the device
    ports:
     - 5000:5000
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    privileged: 
      true                                      # necessary to access the serial device
    pid:
      "host"                                    # necessary to reboot/shutdown from within the container

volumes:
  database:
    name: database
    driver: local
  static:
    name: static
    driver: local
  saves:
    name: saves
    driver: local
  autodetect:
    name: autodetect
    driver: local
  logs:
    name: logs
    driver: local