"""Adding drawing path lenght for ETA

Revision ID: 05007b246e56
Revises: 2f4ab5178ba3
Create Date: 2021-04-06 15:30:50.963976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05007b246e56'
down_revision = '2f4ab5178ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ids_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_name', sa.String(length=20), nullable=False),
    sa.Column('last_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_name')
    )

    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dimensions_info', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('path_length', sa.Float(), nullable=True))
    
    # ### end Alembic commands ###

    # setting up a sequence in the id column
        batch_op.add_column(sa.Column('tmp_id', sa.Integer(), sa.Sequence("uploaded_id")))
        sa.PrimaryKeyConstraint("tmp_id")

    op.execute("UPDATE uploaded_files SET tmp_id=id")

    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_column("id")
        # FIXME don't understand why this is not working: should create always a new id, instead is reusing the highest possible non used id (even if it was already used and then deleted). For the moment can create a new table with the last id and increment that every time a new drawing is uploaded (not a real solution, more like a workaround, I don't like it)
        # This should fix issue #40 which is due to the cached image being loaded (because it is reusing an old id)
        batch_op.add_column(sa.Column('id', sa.Integer(), sa.Sequence("uploaded_id"), autoincrement=True, primary_key=True))
    
    op.execute("UPDATE uploaded_files SET id=tmp_id")
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_column("tmp_id")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ids_sequences')
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_column('path_length')
        batch_op.drop_column('dimensions_info')

    # ### end Alembic commands ###
