"""empty message

Revision ID: 66d9df74c26a
Revises: 
Create Date: 2020-09-08 20:49:14.617499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66d9df74c26a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('edit_date', sa.DateTime(), nullable=True),
    sa.Column('drawings', sa.String(length=1000), nullable=True),
    sa.Column('options', sa.String(length=1000), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=80), nullable=False),
    sa.Column('up_date', sa.DateTime(), nullable=False),
    sa.Column('edit_date', sa.DateTime(), nullable=True),
    sa.Column('last_drawn_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploaded_files')
    op.drop_table('playlists')
    # ### end Alembic commands ###
