"""Initial migration

Revision ID: bf3bbfa3c751
Revises: 
Create Date: 2020-10-11 16:22:00.268343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3bbfa3c751'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('edit_date', sa.DateTime(), nullable=True),
    sa.Column('elements', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=80), nullable=False),
    sa.Column('up_date', sa.DateTime(), nullable=False),
    sa.Column('edit_date', sa.DateTime(), nullable=True),
    sa.Column('last_drawn_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploaded_files')
    op.drop_table('playlists')
    # ### end Alembic commands ###
